name: create-repo
on:
  workflow_dispatch:
    inputs:
      prefix:
        description: '레포 prefix 설정'
        required: true
        default: 'service'
        type: choice
        options:
          - example
          - service
      name:
        description: '레포 이름 설정'
        required: true
        default: 'github-actions'
        type: string

jobs:
  create-repo-automation:
    runs-on: ubuntu-latest
    steps:
      - name: gh auth login
        run: echo ${{ secrets.PERSONAL_ACCESS_TOKEN }} | gh auth login --with-token
      - name: create-repo
        id: create-repo
        run: gh repo create soplay-action/${{ inputs.prefix }}-${{ inputs.name }} --public --add-readme
      - name: webhook notification ( Discord )
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.WEBHOOK_URL }}
          nodetail: true
          title: '레포 생성'
          content: <@${{ secrets.DISCORD_ID }}>
          status: ${{ steps.create-repo.outcome }}
          description: |
            RepoName : `${{ inputs.prefix }}-${{ inputs.name }}`
            RepoLink :  [soplay-action/${{ inputs.prefix }}-${{ inputs.name }}](https://github.com/soplay-action/${{ inputs.prefix }}-${{ inputs.name }})
