name: string-funtion
on: push

jobs:
  string-function:
    runs-on: ubuntu-Latest
    steps:
      - name: startswith
        if: startswith('github actions', 'git')
        run: echo "git"
      - name: startswith
        if: startswith('github actions', 'test')
        run: echo "test"

      - name: endswith
        if: endswith('github actions', 'ions')
        run: echo "ions"
      - name: endsWith
        if: endswith('github actions', 'test')
        run: echo "test"

      - name: contains
        if: contains('github actions', 'act')
        run: echo "contains act"
      - name: startswith
        if: contains('github, actions', 'git')
        run: echo "contains git"
