name: cache-with-bun-react
on:
  push:
    paths:
      - 'my-app/**'

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup-bun
        uses: oven-sh/setup-bun
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.bun
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-
      - name: Install deps
        run: |
          cd my-app
          bun i
      - name: Build react-app
        run: |
          cd my-app
          bun run build
