name: cicd-1
on:
  pull_request:
    types: [opened, synchronize, closed]
    branches: [dev]
    paths:
      - 'my-app/**'

env:
  react-dir: my-app

jobs:
  test:
    if: github.event.action == 'opened' || github.event.action == 'synchronize'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v3
        with:
          key: ${{runner.os}}-bun-${{hashFiles('**/bun.lockb')}}
          restore-keys: ${{runner.os}}-bun-
          path: |
            ~/.bun
            **/node_modules
      - name: install deps
        run: bun i
        working-directory: ${{env.react-dir}}
      - name: run test
        run: bun run test
        working-directory: ${{env.react-dir}}

  image-build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

  deploy:
    runs-on: ubuntu-latest
    needs: image-build
    steps:
      - name: checkout
        uses: actions/checkout@v4
