name: needs
on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "job1 done"

  job2:
    needs: [job1]
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "job2 done"
  job3:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo "job3 failed"
          exit 1
  job4:
    needs: [job3]
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "job4 done"
