name: path-filter
on:
  push:
    paths:
      - '.github/workflows/part1/*'
      - '!.github/workflows/part1/push.yaml' # 특정 경로를 제외함

jobs:
  path-filter:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo hello
